name: CI
on:
  push:
    branches: [ "main" ]
   pull_request:
    branches: [ "main" ]
 
  
  workflow_dispatch:
    inputs:
     my_input:
      required: true
      default: Deploy
      description: "this is test workflow"
      type: choice
      option :
       - Deploy
       - Destroy          

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Extract tag info
      id: extract_tag
      run: |
        BRANCH=release
        TAG=24.3.0
        AZURE_REGION=canadacentral
        CUSTOMER_FULL_NAME=AutoQA
        echo "AZURE_REGION=$AZURE_REGION" >> $GITHUB_ENV
        echo "CUSTOMER_FULL_NAME=$CUSTOMER_FULL_NAME" >> $GITHUB_ENV


    - name: Set environment variables
      run: |
        echo "Setting environment variables"
        echo "CUSTOMER_KEY=${{ secrets.CUSTOMER_KEY }}" >> $GITHUB_ENV
        echo "IMAGE_VERSION=${{ secrets.IMAGE_VERSION }}" >> $GITHUB_ENV
        echo "PRODUCT_TYPE=${{ secrets.PRODUCT_TYPE }}" >> $GITHUB_ENV

    # Deploy to Azure
    - name: Deploy Azure resources
      run: |
        echo "Deploying to Azure region: $AZURE_REGION for customer: $CUSTOMER_FULL_NAME"
        az deployment group create --resource-group $CUSTOMER_FULL_NAME-rg \
                                   --template-file ./azuredeploy.json \
                                   --parameters customerName=$CUSTOMER_FULL_NAME \
                                                customerKey=$CUSTOMER_KEY \
                                                imageVersion=$IMAGE_VERSION \
                                                productType=$PRODUCT_TYPE \
      
